FORMAT: 1A
HOST: http://boardgamedb.me/

# boardgamedb

This API will display general info about a collection of board games such as their developer(s), genre, and the mechanics they have as well as events for players to meet up and enjoy board games.

## Games [/api/games?page={int}&per_page={int}&sort={str}]

These call provide information for the specific games in our database. 

### List All Board Games [GET] 

+ Response 200 (application/json)

    
        {
            "page": 1, 
            "results": [
                {
                  "alt_names": [], 
                  "artists": [
                    [
                      87934, 
                      "Anton Khozyaenko"
                    ]
                  ], 
                  "desc": "1% is a deckbuilding game...", 
                  "developers": [
                    [
                      87933, 
                      "Bryan M. Simmons"
                    ]
                  ], 
                  "families": [
                    [
                      8374, 
                      "Crowdfunding: Kickstarter"
                    ],...
                  ], 
                  "genres": [
                    [
                      1002, 
                      "Card Game"
                    ]
                  ], 
                  "id": 190608, 
                  "img": "https://cf.geekdo-images.com/images/pic2826605.png", 
                  "is_expansion": false, 
                  "max_players": 8, 
                  "mechanics": [
                    [
                      2015, 
                      "Variable Player Powers"
                    ],...
                  ], 
                  "min_players": 1, 
                  "name": "1%", 
                  "publishers": [
                    [
                      31326, 
                      "Rolling Outlaw Games"
                    ]
                  ], 
                  "rating": 10.0, 
                  "year": 0
                }, ...
            ],
            "total_pages"=167
        }

        
### Show Data for One Game [GET /api/games/{id}]

+ Parameters
    + id (required, int, `1`) ... Game ID


+ Response 200 (application/json)

        {
            "alt_names": [], 
            "artists": [
                [
                    12517, 
                    "Marcus Gschwendtner"
                ]
            ], 
            "desc": "Die Macher is a game ...", 
            "developers": [
                [
                    1, 
                    "Karl-Heinz Schmiel"
                ]
            ], 
            "families": [
                [
                    91, 
                    "Valley Games Classic Line"
                ], ...
            ], 
            "genres": [
                [
                    1001, 
                    "Political"
                ], ...
            ], 
            "id": 1, 
            "img": "https://cf.geekdo-images.com/images/pic159509.jpg", 
            "is_expansion": false, 
            "max_players": 5, 
            "mechanics": [
                [
                    2012, 
                    "Auction/Bidding"
                ], ...
            ], 
            "min_players": 3, 
            "name": "Die Macher", 
            "publishers": [
                [
                    2, 
                    "Moskito Spiele"
                ], ...
            ], 
            "rating": 7.65648, 
            "year": 1986
        }

### Show All Board Game Names[GET /api/games/names]

+ Response 200 (application/json)

        [
          [
            1, 
            "Die Macher"
          ],...
        ]


## Developers [/api/developers?page={int}&per_page={int}&sort={str}]

These calls provide information about the board game developers in our database.

### List All Developers [GET] 

+ Response 200 (application/json)

        {
            "page": 1, 
            "results": [
                {
                  "desc": null, 
                  "games": [], 
                  "genres": [], 
                  "id": 8996, 
                  "img": "https://cf.geekdo-images.com/images/pic1657690_t.jpg", 
                  "name": "\"Eclaireur\"", 
                  "website": null
                },...
            ],
            "total_pages": 1275
        }

        
### Show Data for One Developer [GET /api/developers/{id}]

+ Parameters
    + id (required, int, `1`) ... Developer ID


+ Response 200 (application/json)

        {
            "desc": "<p><strong>Karl-Heinz Schmiel</strong> (born November 28, 1948) ...", 
            "games": [
                [
                    1, 
                    "Die Macher"
                ], ...
            ], 
            "genres": [
                [
                    1001, 
                    "Political"
                ], ...
            ], 
            "id": 1, 
            "img": "https://cf.geekdo-images.com/images/pic477390_t.jpg", 
            "name": "Karl-Heinz Schmiel", 
            "website": "http://..."
        }  

### Show All Developers Names[GET /api/developers/names]

+ Response 200 (application/json)

        [
          [
            1, 
            "Karl-Heinz Schmiel"
          ],...
        ]


## Genres [/api/genres?page={int}&per_page={int}&sort={str}]

These calls provide data of all the genres that our games fall under. 

### List All Genres [GET] 

+ Response 200 (application/json)

        {
            "page": 1, 
            "results":
            [
                {
                    "desc": "<p><em>Political</em> games encourage ...", 
                    "developers": [
                        [
                            1, 
                            "Karl-Heinz Schmiel"
                        ], ...
                    ], 
                    "events": [], 
                    "games": [
                        [
                            1, 
                            "Die Macher"
                        ], ..
                    ], 
                    "id": 1001, 
                    "img": "https://cf.geekdo-images.com/images/pic1657689_t.jpg", 
                    "name": "Political"
                }, ...
            ],
            "total_pages": 5
        }


### Show Data for One Genre [GET /api/genres/{id}]

+ Parameters
    + id (required, int, `1`) ... Genre ID


+ Response 200 (application/json)

        {
            "desc": "<p><em>Political</em> games encourage ...", 
            "developers": [
                [
                    1, 
                    "Karl-Heinz Schmiel"
                ], ...
            ], 
            "events": [], 
            "games": [
                [
                    1, 
                    "Die Macher"
                ], ..
            ], 
            "id": 1001, 
            "img": "https://cf.geekdo-images.com/images/pic1657689_t.jpg", 
            "name": "Political"
        }

### Show All Genres Names[GET /api/genres/names]

+ Response 200 (application/json)

        [
          [
            1001, 
            "Political"
          ],...
        ]

## Events [/api/events?page={int}&per_page={int}&sort={str}]

These calls provide information about the board game events in our database.

### List All Events [GET] 

+ Response 200 (application/json)

        {
            "page": 1, 
            "results":[
            {
                "desc": "<p>Come and join us ...", 
                "games": [], 
                "genres": [
                    [
                        1019, 
                        "Wargame"
                    ], ...
                ], 
                "id": 1, 
                "img": "https://cf.geekdo-images.com/images/pic1657689_t.jpg", 
                "link": "https://www.meetup.com/SABoardGamers/events/244392199/", 
                "location": "San Antonio, TX", 
                "name": "SA Board Gamers Thursday night gaming", 
                "time": "Thu, 26 Oct 2017 18:00:00 GMT"
            }, ...
            ],
            "total_pages": 40
        }
        
        
### Show Data for One Event [GET /api/events/{id}]

+ Parameters
    + id (required, int, `1`) ... Event ID


+ Response 200 (application/json)

        {
            "desc": "<p>Come and join us ...", 
            "games": [], 
            "genres": [
                [
                    1019, 
                    "Wargame"
                ], ...
            ], 
            "id": 1, 
            "img": "https://cf.geekdo-images.com/images/pic1657689_t.jpg", 
            "link": "https://www.meetup.com/SABoardGamers/events/244392199/", 
            "location": "San Antonio, TX", 
            "name": "SA Board Gamers Thursday night gaming", 
            "time": "Thu, 26 Oct 2017 18:00:00 GMT"
        }

### Show All Events Names[GET /api/events/names]

+ Response 200 (application/json)

        [
          [
            1, 
            "SA Board Gamers Thursday night gaming"
          ],...
        ]
        
## Search [/api/search?query={string}&page={int}]

This call provides search functionality to our website.

### Search Model Instance by Attribute [GET]
    
+ Response 200 (application/json)

        {
            “results”: [{
                    “id”: 13,
                    “score”: 25.123412634,
                    “type”: “Game”
                },
                {
                    “id”: 5,
                    “score”: 20.12341234,
                    “type”: “Event”
                }
                ...
            ]
        }