runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    mysql+pymysql://root:boardgamers@/proddata?unix_socket=/cloudsql/boardgamedb-181002:us-central1:boardgamedb-data

beta_settings:
  cloud_sql_instances: boardgamedb-181002:us-central1:boardgamedb-data